# -*- coding: utf-8 -*-
"""coffeetest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vLxJZm78u_aYebZFoz47RhqvpFCdssmc
"""

import sklearn
import pandas as pd


from google.colab import drive
drive.mount('/content/Data-coffee-shop-1month')

!ls